// frontend/src/components/HealthForm.jsx
import React, { useState } from "react";
import axios from "axios";

function HealthForm() {
  const [formData, setFormData] = useState({
    user_id: 1,
    heart_rate: 0.0,
    sleep_hours: 0.0,
    stress_level: 0.0,
  });

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post('http://localhost:8000/health', formData);
      // onAdd(res.data);
      setFormData({ ...formData, heart_rate: 0.0, sleep_hours: 0.0, stress_level: 0.0 });
    } catch (e) {
      console.error("error saving metric:", e);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <h3>Add Health Metric</h3>
      <label name="heart_rate">Heart Rate</label>
      <input
        type="number"
        name="heart_rate"
        placeholder="Heart Rate"
        value={formData.heart_rate}
        onChange={handleChange}
        required
      />
      <label name="sleep_hours">Sleep Hours</label>
      <input
        type="number"
        name="sleep_hours"
        placeholder="Sleep Hours"
        value={formData.sleep_hours}
        onChange={handleChange}
        required
      />
      <label name="stress_level">Stress Level</label>
      <input
        type="number"
        name="stress_level"
        placeholder="Stress Level"
        value={formData.stress_level}
        onChange={handleChange}
        required
      />
      <button type="submit">Save</button>
    </form>
  )
}

export default HealthForm;

// frontend/src/components/HealthForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <input v-model.number="user_id" type="number" placeholder="User ID" required />
    <input v-model.number="heart_rate" type="number" step="0.1" placeholder="Heart Rate" required />
    <input v-model.number="sleep_hours" type="number" step="0.1" placeholder="Sleep Hours" required />
    <input v-model.number="stress_level" type="number" step="0.1" placeholder="Stress Level" required />
    <button type="submit">Aggiungi metrica</button>
    <p v-if="message">{{ message }}</p>
  </form>
</template>

<script>
  import { ref } from "vue";
  import { createHealthData } from "../services/api.js"

  export default {
    setup() {
      const user_id = ref(1);
      const heart_rate = ref(0);
      const sleep_hours = ref(0);
      const stress_level = ref(0);

      const message = ref("");

      const handleSubmit = async () => {
        try {
          const res = await createHealthData({ user_id: user_id.value, heart_rate: heart_rate.value, sleep_hours: sleep_hours.value, stress_level: stress_level.value });
          message.value = `Metrica creata con ID: ${res.data.id}`;
        } catch(e) {
          message.value = "Errore: " + e.response.data.detail || e.message
        }
      };
      
      return { user_id, heart_rate, sleep_hours, stress_level, handleSubmit, message };
    },
  };
</script>
